name: Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-and-test:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                experimental: [false] # Shadow CI Jobs
                node: ['15', '14', '12'] # Refer to https://nodejs.org/en/about/releases/ for supported versions
                include:
                    - node: '16'
                      experimental: true

        name: Test on Node v${{ matrix.node }}
        continue-on-error: ${{ matrix.experimental }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2.1.5
                with:
                    node-version: ${{ matrix.node }}

            -   name: Cache node modules
                uses: actions/cache@v2
                id: cache-modules
                env:
                    cache-name: cache-node-${{ matrix.node }}-modules
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-

            -   name: Cache node modules for docs
                uses: actions/cache@v2
                id: cache-docs-modules
                env:
                    cache-name: cache-node-${{ matrix.node }}-modules-docs
                with:
                    path: ./docs/node_modules
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./docs/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-

            -   name: Install dependencies
                if: steps.cache-modules.outputs.cache-hit != 'true'
                run: yarn install --prefer-offline --frozen-lockfile

            -   name: Install dependencies for docs
                if: steps.cache-docs-modules.outputs.cache-hit != 'true'
                run: yarn --cwd ./docs install --prefer-offline --frozen-lockfile

            -   name: Build package
                run: yarn build

            -   name: Run tests
                run:
                    yarn test
